.PHONY: clean All

All:
	@echo "----------Building project:[ Search & Sort - Debug ]----------"
	@"$(MAKE)" -f  "Search & Sort.mk"
clean:
	@echo "----------Cleaning project:[ Search & Sort - Debug ]----------"
	@"$(MAKE)" -f  "Search & Sort.mk" clean
